/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.lp2.muebleria2025.vista;


import com.lp2.muebleria2025.controlador.CalendarioController;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;

/**
 *
 * @author HP
 */
public class GUIMovimientosF extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public GUIMovimientosF() {
        initComponents();
        setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
        this.setTitle("NUEVA VENTA CONTADO");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        txt_buscar = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panel_ingresos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_ingresos = new javax.swing.JTable();
        panel_egresos = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_egresos = new javax.swing.JTable();
        panel_cobrar = new javax.swing.JPanel();
        panel_pagar = new javax.swing.JPanel();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        btn_calendar3 = new javax.swing.JButton();
        txt_desde = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_hasta = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btn_calendar1 = new javax.swing.JButton();
        lp_gastos = new javax.swing.JLayeredPane();
        jLabel5 = new javax.swing.JLabel();
        lb_gastos = new javax.swing.JLabel();
        lp_ventas = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        lb_ventas = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lp_balance = new javax.swing.JLayeredPane();
        lb_balance = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_buscar1 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();

        jMenuItem4.setText("jMenuItem4");

        jMenuItem5.setText("jMenuItem5");

        jMenuItem6.setText("jMenuItem6");

        jMenuItem11.setText("jMenuItem11");

        jMenuItem12.setText("jMenuItem12");

        jMenuItem13.setText("jMenuItem13");

        txt_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_buscarActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(200, 200));

        table_ingresos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table_ingresos);

        javax.swing.GroupLayout panel_ingresosLayout = new javax.swing.GroupLayout(panel_ingresos);
        panel_ingresos.setLayout(panel_ingresosLayout);
        panel_ingresosLayout.setHorizontalGroup(
            panel_ingresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1185, Short.MAX_VALUE)
        );
        panel_ingresosLayout.setVerticalGroup(
            panel_ingresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_ingresosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Ingresos", panel_ingresos);

        table_egresos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(table_egresos);

        javax.swing.GroupLayout panel_egresosLayout = new javax.swing.GroupLayout(panel_egresos);
        panel_egresos.setLayout(panel_egresosLayout);
        panel_egresosLayout.setHorizontalGroup(
            panel_egresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_egresosLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );
        panel_egresosLayout.setVerticalGroup(
            panel_egresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_egresosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Egresos", panel_egresos);

        javax.swing.GroupLayout panel_cobrarLayout = new javax.swing.GroupLayout(panel_cobrar);
        panel_cobrar.setLayout(panel_cobrarLayout);
        panel_cobrarLayout.setHorizontalGroup(
            panel_cobrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1185, Short.MAX_VALUE)
        );
        panel_cobrarLayout.setVerticalGroup(
            panel_cobrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 228, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Por Cobrar", panel_cobrar);

        javax.swing.GroupLayout panel_pagarLayout = new javax.swing.GroupLayout(panel_pagar);
        panel_pagar.setLayout(panel_pagarLayout);
        panel_pagarLayout.setHorizontalGroup(
            panel_pagarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1185, Short.MAX_VALUE)
        );
        panel_pagarLayout.setVerticalGroup(
            panel_pagarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 228, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Por Pagar", panel_pagar);

        ImageIcon iconoOriginal = new ImageIcon(getClass().getResource("/iconos/calendar_month_16dp_789DE5_FILL0_wght400_GRAD0_opsz20.png"));
        Image imagenEscalada = iconoOriginal.getImage().getScaledInstance(20, 20, Image.SCALE_SMOOTH); // Tamaño 32x32
        btn_calendar3.setIcon(new ImageIcon(imagenEscalada));
        btn_calendar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calendar3ActionPerformed(evt);
            }
        });

        txt_desde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_desdeActionPerformed(evt);
            }
        });

        jLabel6.setText("Desde:");

        jLabel7.setText("Hasta:");

        btn_calendar1.setIcon(new ImageIcon(imagenEscalada));
        btn_calendar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calendar1ActionPerformed(evt);
            }
        });

        lp_gastos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lp_gastos.setPreferredSize(new java.awt.Dimension(240, 60));

        jLabel5.setText("Gastos Totales");

        lb_gastos.setBackground(new java.awt.Color(0, 0, 0));
        lb_gastos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_gastos.setForeground(new java.awt.Color(204, 0, 0));
        lb_gastos.setText("0");

        lp_gastos.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_gastos.setLayer(lb_gastos, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout lp_gastosLayout = new javax.swing.GroupLayout(lp_gastos);
        lp_gastos.setLayout(lp_gastosLayout);
        lp_gastosLayout.setHorizontalGroup(
            lp_gastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lp_gastosLayout.createSequentialGroup()
                .addGroup(lp_gastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lp_gastosLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(lb_gastos))
                    .addGroup(lp_gastosLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel5)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        lp_gastosLayout.setVerticalGroup(
            lp_gastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lp_gastosLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(lb_gastos)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        lp_ventas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lp_ventas.setPreferredSize(new java.awt.Dimension(240, 60));

        jLabel1.setText("Ventas Totales");

        lb_ventas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_ventas.setForeground(new java.awt.Color(0, 153, 51));
        lb_ventas.setText("0");

        jLabel8.setIcon(new ImageIcon(AjustarImg ("/iconos/ventas_icon.png", 30, 30)));
        jLabel8.setForeground(new java.awt.Color(0, 153, 51));

        lp_ventas.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_ventas.setLayer(lb_ventas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_ventas.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout lp_ventasLayout = new javax.swing.GroupLayout(lp_ventas);
        lp_ventas.setLayout(lp_ventasLayout);
        lp_ventasLayout.setHorizontalGroup(
            lp_ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lp_ventasLayout.createSequentialGroup()
                .addGroup(lp_ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lp_ventasLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel1))
                    .addGroup(lp_ventasLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(lb_ventas)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        lp_ventasLayout.setVerticalGroup(
            lp_ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lp_ventasLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGroup(lp_ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lp_ventasLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lb_ventas))
                    .addGroup(lp_ventasLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        lp_balance.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lp_balance.setPreferredSize(new java.awt.Dimension(240, 60));

        lb_balance.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_balance.setText("0");

        jLabel2.setText("Balance");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/historial1.png"))); // NOI18N

        lp_balance.setLayer(lb_balance, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_balance.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lp_balance.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout lp_balanceLayout = new javax.swing.GroupLayout(lp_balance);
        lp_balance.setLayout(lp_balanceLayout);
        lp_balanceLayout.setHorizontalGroup(
            lp_balanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lp_balanceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(66, 66, 66)
                .addGroup(lp_balanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lp_balanceLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lb_balance))
                    .addComponent(jLabel2))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        lp_balanceLayout.setVerticalGroup(
            lp_balanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lp_balanceLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(lp_balanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_balance)
                    .addComponent(jLabel4))
                .addGap(24, 24, 24))
        );

        jLabel3.setText("Buscar Concepto");

        txt_buscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_buscar1ActionPerformed(evt);
            }
        });

        jLayeredPane3.setLayer(btn_calendar3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(txt_desde, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(txt_hasta, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(btn_calendar1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(lp_gastos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(lp_ventas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(lp_balance, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(txt_buscar1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_desde, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(btn_calendar1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_hasta, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_calendar3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_buscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addComponent(lp_balance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(lp_ventas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(lp_gastos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_calendar1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_calendar3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_hasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_desde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_buscar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addGap(42, 42, 42)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lp_balance, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                    .addComponent(lp_ventas, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                    .addComponent(lp_gastos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
                .addContainerGap())
        );

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_calendar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calendar3ActionPerformed
        // TODO add your handling code here:
        calendario(txt_hasta);
    }//GEN-LAST:event_btn_calendar3ActionPerformed

    private void txt_desdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_desdeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_desdeActionPerformed

    private void btn_calendar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calendar1ActionPerformed
        // TODO add your handling code here:
        calendario(txt_desde);
    }//GEN-LAST:event_btn_calendar1ActionPerformed

    private void txt_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_buscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_buscarActionPerformed

    private void txt_buscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_buscar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_buscar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIMovimientosF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIMovimientosF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIMovimientosF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIMovimientosF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIMovimientosF().setVisible(true);
            }
        });
    }
    
     private void calendario (JTextField txt){
        GUICalendario guicalen = new GUICalendario (null, true);
        CalendarioController calenCtrl = new CalendarioController(guicalen, txt);
        calenCtrl.mostrarVentana();
    }
    
    Image AjustarImg (String img, int x, int y){
        ImageIcon iconoOriginal = new ImageIcon(getClass().getResource(img));
        Image imagenEscalada = iconoOriginal.getImage().getScaledInstance(x, y, Image.SCALE_SMOOTH);
        return imagenEscalada;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_calendar1;
    public javax.swing.JButton btn_calendar3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JLabel lb_balance;
    public javax.swing.JLabel lb_gastos;
    public javax.swing.JLabel lb_ventas;
    public javax.swing.JLayeredPane lp_balance;
    public javax.swing.JLayeredPane lp_gastos;
    public javax.swing.JLayeredPane lp_ventas;
    public javax.swing.JPanel panel_cobrar;
    public javax.swing.JPanel panel_egresos;
    public javax.swing.JPanel panel_ingresos;
    private javax.swing.JPanel panel_pagar;
    public javax.swing.JTable table_egresos;
    public javax.swing.JTable table_ingresos;
    public javax.swing.JTextField txt_buscar;
    public javax.swing.JTextField txt_buscar1;
    public javax.swing.JTextField txt_desde;
    public javax.swing.JTextField txt_hasta;
    // End of variables declaration//GEN-END:variables
}
