/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.lp2.muebleria2025.vista;

import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import com.lp2.muebleria2025.controlador.ClienteController;
import com.lp2.muebleria2025.controlador.DetallesVentasController;
import com.lp2.muebleria2025.controlador.IvaController;
import com.lp2.muebleria2025.controlador.MarcaController;
import com.lp2.muebleria2025.controlador.NuevoUsuarioController;
import com.lp2.muebleria2025.controlador.ProductoController;
import com.lp2.muebleria2025.controlador.ProveedorController;
import com.lp2.muebleria2025.controlador.UsuarioController;
import com.lp2.muebleria2025.controlador.VentasController;
import com.lp2.muebleria2025.modelo.dao.ClienteCrudImpl;
import com.lp2.muebleria2025.modelo.dao.DescuentosCrudImpl;
import com.lp2.muebleria2025.controlador.DescuentosController;
import com.lp2.muebleria2025.modelo.DetalleVentas;
import com.lp2.muebleria2025.modelo.dao.Conexion;
import com.lp2.muebleria2025.modelo.dao.DetalleVentasCrudImpl;
import com.lp2.muebleria2025.modelo.dao.IvaCrudImpl;
import com.lp2.muebleria2025.modelo.dao.MarcaCrudImpl;
import com.lp2.muebleria2025.modelo.dao.ProductoCrudImpl;
import com.lp2.muebleria2025.modelo.dao.ProveedorCrudImpl;
import com.lp2.muebleria2025.modelo.dao.UsuarioCrudImpl;
import com.lp2.muebleria2025.modelo.dao.VentasCrudImpl;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author HP
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    Connection conec;
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        this.setTitle("SISTEMA DE VENTAS v.1.0  Usuario activo: "+UsuarioCrudImpl.nombre + " " + UsuarioCrudImpl.apellido);
        if (!"ADMINISTRADOR".equals(UsuarioCrudImpl.rol_usuario) && !"GERENTE".equals(UsuarioCrudImpl.rol_usuario)){
            this.usuario_jmenu.setEnabled(false);
            this.producto_jMenu.setEnabled(false);
            this.proveedores_jMenu.setEnabled(false);
            //this.Clientes_jMenu.setEnabled(false);
            this.reportes_jMenu.setEnabled(false);
        }else{
           this.usuario_jmenu.setEnabled(true);
           this.producto_jMenu.setEnabled(true);
           this.proveedores_jMenu.setEnabled(true);
            //this.Clientes_jMenu.setEnabled(false);
            this.reportes_jMenu.setEnabled(true);
        }
        this.jMenu_categoria.setVisible(false);
        this.jMenu_categoria.setEnabled(false);
        
        this.jMenu_iva.setVisible(false);
        this.jMenu_iva.setEnabled(false);
        System.out.println(UsuarioCrudImpl.rol_usuario);
        Conexion conectar = new Conexion();
        conec = conectar.conectarBD();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jToggleButtonTema = new javax.swing.JToggleButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        usuario_jmenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        Clientes_jMenu = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        proveedores_jMenu = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        producto_jMenu = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu_iva = new javax.swing.JMenuItem();
        jMenu_categoria = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem18 = new javax.swing.JMenuItem();
        reportes_jMenu = new javax.swing.JMenu();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem19 = new javax.swing.JMenuItem();

        jMenuItem4.setText("jMenuItem4");

        jMenuItem5.setText("jMenuItem5");

        jMenuItem6.setText("jMenuItem6");

        jMenuItem11.setText("jMenuItem11");

        jMenuItem12.setText("jMenuItem12");

        jMenuItem13.setText("jMenuItem13");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToggleButtonTema.setText("👁");
        jToggleButtonTema.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButtonTema.setMaximumSize(new java.awt.Dimension(30, 30));
        jToggleButtonTema.setMinimumSize(new java.awt.Dimension(30, 30));
        jToggleButtonTema.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButtonTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonTemaActionPerformed(evt);
            }
        });

        usuario_jmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        usuario_jmenu.setText("Usuario");
        usuario_jmenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        usuario_jmenu.setMinimumSize(new java.awt.Dimension(130, 50));
        usuario_jmenu.setPreferredSize(new java.awt.Dimension(110, 50));

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo-cliente.png"))); // NOI18N
        jMenuItem1.setText("Nuevo Usuario");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        usuario_jmenu.add(jMenuItem1);

        jMenuItem10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/anadir.png"))); // NOI18N
        jMenuItem10.setText("Lista Usuarios");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        usuario_jmenu.add(jMenuItem10);

        jMenuBar1.add(usuario_jmenu);

        Clientes_jMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cliente.png"))); // NOI18N
        Clientes_jMenu.setText("Clientes");
        Clientes_jMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Clientes_jMenu.setMinimumSize(new java.awt.Dimension(130, 50));
        Clientes_jMenu.setPreferredSize(new java.awt.Dimension(110, 50));

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo-producto.png"))); // NOI18N
        jMenuItem2.setText("Administrar Clientes");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        Clientes_jMenu.add(jMenuItem2);

        jMenuBar1.add(Clientes_jMenu);

        proveedores_jMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cliente.png"))); // NOI18N
        proveedores_jMenu.setText("Proveedores");
        proveedores_jMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        proveedores_jMenu.setMinimumSize(new java.awt.Dimension(130, 50));
        proveedores_jMenu.setPreferredSize(new java.awt.Dimension(130, 50));

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo-producto.png"))); // NOI18N
        jMenuItem3.setText("Administrar Proveedores");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        proveedores_jMenu.add(jMenuItem3);

        jMenuBar1.add(proveedores_jMenu);

        producto_jMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/producto.png"))); // NOI18N
        producto_jMenu.setText("Producto");
        producto_jMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        producto_jMenu.setPreferredSize(new java.awt.Dimension(130, 50));

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo-producto.png"))); // NOI18N
        jMenuItem7.setText("Administrar Productos");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        producto_jMenu.add(jMenuItem7);

        jMenu_iva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/anadir.png"))); // NOI18N
        jMenu_iva.setText("Iva");
        jMenu_iva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_ivaActionPerformed(evt);
            }
        });
        producto_jMenu.add(jMenu_iva);

        jMenu_categoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/categorias.png"))); // NOI18N
        jMenu_categoria.setText("Categoría");
        jMenu_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_categoriaActionPerformed(evt);
            }
        });
        producto_jMenu.add(jMenu_categoria);

        jMenuItem17.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/configuraciones.png"))); // NOI18N
        jMenuItem17.setText("Descuentos");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        producto_jMenu.add(jMenuItem17);

        jMenuBar1.add(producto_jMenu);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/categorias.png"))); // NOI18N
        jMenu5.setText("Facturacion");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenu5.setPreferredSize(new java.awt.Dimension(130, 50));

        jMenuItem14.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/venta.png"))); // NOI18N
        jMenuItem14.setText("Compras");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem14);

        jMenuItem15.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carrito.png"))); // NOI18N
        jMenuItem15.setText("Ventas");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem15);

        jMenuBar1.add(jMenu5);

        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reporte1.png"))); // NOI18N
        jMenu8.setText("Movimientos");
        jMenu8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenu8.setPreferredSize(new java.awt.Dimension(130, 50));

        jMenuItem18.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/historial1.png"))); // NOI18N
        jMenuItem18.setText("Movimientos");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem18);

        jMenuBar1.add(jMenu8);

        reportes_jMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reportes.png"))); // NOI18N
        reportes_jMenu.setText("Reportes");
        reportes_jMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        reportes_jMenu.setMinimumSize(new java.awt.Dimension(130, 50));
        reportes_jMenu.setPreferredSize(new java.awt.Dimension(110, 50));

        jMenuItem16.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carrito.png"))); // NOI18N
        jMenuItem16.setText("Reporte de Ventas Contado");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        reportes_jMenu.add(jMenuItem16);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/producto.png"))); // NOI18N
        jMenuItem8.setText("Lista de Productos");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        reportes_jMenu.add(jMenuItem8);

        jMenuBar1.add(reportes_jMenu);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar-sesion.png"))); // NOI18N
        jMenu7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenu7.setPreferredSize(new java.awt.Dimension(40, 50));
        jMenu7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu7ActionPerformed(evt);
            }
        });

        jMenuItem19.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItem19.setText("Cerrar Sesión");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem19);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToggleButtonTema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1171, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToggleButtonTema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(521, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        GUIProducto producto = new GUIProducto(null, true);
        ProductoCrudImpl crud = new ProductoCrudImpl();
        ProductoController ctrl = new ProductoController(producto, crud);
        ctrl.mostrarVentana();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jToggleButtonTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonTemaActionPerformed
        // TODO add your handling code here:
        if (jToggleButtonTema.isSelected()) {
            FlatMacDarkLaf.setup(); // Cambiar a tema oscuro
            jToggleButtonTema.setToolTipText("Cambiar a Tema Claro");
        } else {
            FlatMacLightLaf.setup(); // Cambiar a tema claro
            jToggleButtonTema.setToolTipText("Cambiar a Tema Oscuro");
        }
            SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_jToggleButtonTemaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        GUINuevoUsuario nusuario = new GUINuevoUsuario(null, true);
        UsuarioCrudImpl crud = new UsuarioCrudImpl();
        NuevoUsuarioController ctrl = new NuevoUsuarioController(nusuario, crud);
        ctrl.mostrarVentana();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        GUIUsuarios usuario = new GUIUsuarios(null, true);
        UsuarioCrudImpl crud = new UsuarioCrudImpl();
        UsuarioController ctrl = new UsuarioController(usuario, crud);
        ctrl.mostrarVentana();
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        GUICliente cliente = new GUICliente(null, true);
        ClienteCrudImpl crud = new ClienteCrudImpl();
        ClienteController ctrl = new ClienteController(cliente, crud);
        ctrl.mostrarVentana();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenu_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_categoriaActionPerformed
        // TODO add your handling code here:
        GUIMarca marca = new GUIMarca(null, true);
        MarcaCrudImpl crud = new MarcaCrudImpl();
        MarcaController ctrl = new MarcaController(marca, crud);
        ctrl.mostrarVentana();
    }//GEN-LAST:event_jMenu_categoriaActionPerformed

    private void jMenu_ivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_ivaActionPerformed
        // TODO add your handling code here:
        GUIIva iva = new GUIIva(null, true);
        IvaCrudImpl crud = new IvaCrudImpl();
        IvaController ctrl = new IvaController(iva, crud);
        ctrl.mostrarVentana();
    }//GEN-LAST:event_jMenu_ivaActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        GUIProveedor proveedor = new GUIProveedor(null, true);
        ProveedorCrudImpl crud = new ProveedorCrudImpl();
        ProveedorController ctrl = new ProveedorController(proveedor, crud);
        ctrl.mostrarVentana();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        // TODO add your handling code here:
       GUIVentasF ventas = new GUIVentasF();
        VentasCrudImpl crud = new VentasCrudImpl();
        VentasController ctrl = new VentasController(ventas, crud);
        
        DetalleVentasCrudImpl d_crud = new DetalleVentasCrudImpl();
        DetallesVentasController d_ctrl = new DetallesVentasController(ventas, d_crud);
        
        ctrl.mostrarVentana(); //Cabezero de Ventas
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        // TODO add your handling code here:
        GUIDescuentos descuento = new GUIDescuentos(null, true);
        DescuentosCrudImpl crud = new DescuentosCrudImpl();
        DescuentosController ctrl = new DescuentosController(descuento, crud);
        ctrl.mostrarVentana();
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenu7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu7ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        // TODO add your handling code here:
        GUIMovimientosF movimientos = new GUIMovimientosF();
        movimientos.setLocationRelativeTo(movimientos);
        movimientos.setVisible(true);
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        // TODO add your handling code here:
        GUIVentas_Contado_R gui = new GUIVentas_Contado_R();
        gui.setLocationRelativeTo(gui);
        gui.setVisible(true);
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        // TODO add your handling code here:
                int ok = JOptionPane.showConfirmDialog(this,
                        "¿Realmente desea Cerrar sesión?", 
                        "Confirmar operacion", 
                        JOptionPane.YES_NO_OPTION, 
                        JOptionPane.QUESTION_MESSAGE);
                if (ok == 0) {
                    this.dispose();
                    GUILogin login = new GUILogin();
                    login.setVisible(true);
                }
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
             System.out.println("Generar Ticket");
        try {
            Map<String, Object> parameters = new HashMap<>(); 
            JasperReport report = JasperCompileManager.compileReport(
                        "C:\\Users\\User\\Documents\\reportes\\lista_productoss.jrxml");
            JasperPrint print = JasperFillManager.fillReport(report, parameters, conec);
            //JasperViewer.viewReport(print, false);
            JasperViewer viewer = new JasperViewer(print, false);
            viewer.setAlwaysOnTop(true); //Muestra la ventana en frente
            viewer.setVisible(true);

            
        } catch (JRException e) {
            Logger.getLogger(GUIVentasF.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Clientes_jMenu;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenu_categoria;
    private javax.swing.JMenuItem jMenu_iva;
    private javax.swing.JToggleButton jToggleButtonTema;
    private javax.swing.JMenu producto_jMenu;
    private javax.swing.JMenu proveedores_jMenu;
    private javax.swing.JMenu reportes_jMenu;
    private javax.swing.JMenu usuario_jmenu;
    // End of variables declaration//GEN-END:variables
}
